// Sinh internal/config/lit_release_data.go từ embedded_release.secret (local, gitignore).
// Chạy: go run ./tools/genlit
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"xkdemo/internal/obf"
)

func main() {
	root, _ := os.Getwd()
	srcPath := filepath.Join(root, "internal", "config", "embedded_release.secret")
	raw, err := os.ReadFile(srcPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genlit: %v (copy embedded_release.secret.example)\n", err)
		os.Exit(1)
	}
	join := strings.TrimSpace(strings.Split(string(raw), "\n")[0])
	if join == "" {
		fmt.Fprintln(os.Stderr, "genlit: embedded_release.secret trống")
		os.Exit(1)
	}

	type pair struct{ name, val string }
	lits := []pair{
		{"encJoin", join},
		{"encAPIBase", "https://api-sgp-oc.xiaomimimo.com/v1"},
		{"encGateway", "https://api.xkiro.com"},
		{"encUA", "mimo-claw"},
		{"encGWPath", "/socket.io"},
		{"encNS", "/gw/mimo"},
	}
	envs := []string{
		"XTR_JOIN", "XTR_GATEWAY_URL", "XTROUTER_GATEWAY_URL",
		"XTR_GATEWAY_SECRET", "XTROUTER_GATEWAY_SECRET", "XTR_GATEWAY_PATH",
		"XTR_ACCOUNT_EMAIL", "MIMO_ACCOUNT_EMAIL", "XIAOMI_ACCOUNT_EMAIL",
		"XTR_LABEL", "HOSTNAME",
		"MIMO_API_KEY", "XIAOMI_MIMO_API_KEY", "MIMO_KEY",
		"MIMO_API_BASE_URL", "MIMO_BASE_URL", "MIMO_ENDPOINT", "MIMO_API_BASE",
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genlit; DO NOT EDIT.\n")
	b.WriteString("//go:build release\n\n")
	b.WriteString("package config\n\n")
	for _, p := range lits {
		fmt.Fprintf(&b, "var %s = []byte{", p.name)
		for i, x := range obf.E(p.val) {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "0x%02x", x)
		}
		b.WriteString("}\n\n")
	}
	b.WriteString("var encEnvNames = [][]byte{\n")
	for _, name := range envs {
		b.WriteString("\t{")
		for i, x := range obf.E(name) {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "0x%02x", x)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	outPath := filepath.Join(root, "internal", "config", "lit_release_data.go")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		formatted = b.Bytes()
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genlit: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("genlit: wrote", strings.TrimPrefix(outPath, root+string(filepath.Separator)))
}
